### PR TITLE
Add emailing feature

### PR DESCRIPTION
**Pull request by daniddelrio**
To test:
- MAKE SURE YOU HAVE THE .ENV FILE
1. Make sure you have a tutor account and a tutee account WITH AN EMAIL YOU HAVE ACCESS TO.
2. Book a session using a tutee account.
3. Accept the session using a tutor account.
4. Using Tutor: Click Sessions in the Navbar > Upcoming. Click Complete Session.
Input a date, start time, and end time indicating the details of the session. Click Complete Session after.
5. Using Tutee: Click Sessions in the Navbar > Unconfirmed. The session should appear there. Click Confirm now to see if the payment amount is finalized.
6. After clicking confirm, check the email of the tutee account to see if an email was sent and the details are correct.

### CODE REVIEW

**Comment by daniddelrio** [comment]
[Automated emailing after session confirmation](https://trello.com/c/mQGDSwGt/9-automated-emailing-after-session-confirmation)

**Comment by LienLeinad** [comment]
not really a bug just a design problem lol
image

**Comment by LienLeinad** [comment]
I'm getting this error in the console when I click confirm session
image

I'm not getting an email from the site as well

**Comment by daniddelrio** [comment]
> not really a bug just a design problem lol
> image

Interesting, I don't see that on my device but it'll look bad for other devices HAHAH I added it as a ticket na. Thanks

**Comment by daniddelrio** [comment]
> I'm getting this error in the console when I click confirm session
> image
> 
> I'm not getting an email from the site as well

What version of Django are you using right now? I Googled and it might be a Django version compatibility problem. I'm using 2.2.5

**Comment by LienLeinad** [comment]
I'm using 2.2.5 din 
image

**Comment by LienLeinad** [comment]
image

**Comment by LienLeinad** [comment]
image

**Comment by daniddelrio** [comment]
[Possible reference for addressing the error](https://github.com/django-helpdesk/django-helpdesk/issues/621)

**Pull request merged**
